-- AlterTable
ALTER TABLE "Account" ADD COLUMN "startingCash" DOUBLE PRECISION NOT NULL DEFAULT 10000;

-- AlterTable
ALTER TABLE "Account" ADD COLUMN "realizedPnl" DOUBLE PRECISION NOT NULL DEFAULT 0;
